As ms sort list
the-collab-lab/tcl-62-smart-shopping-list pull request #26
Opened 2023-09-20 17:52 UTC by MagdaSlifierz

## Description

Implementing a feature that categorizes items into four groups based on how soon the user needs to buy them. 

We created new UI elements for user clarity and developed the logic for sorting items behind the scenes

## Related Issue

closes#12
## Acceptance Criteria

- [x] Items in the list are shown with an indicator that tells the user they should buy the item “soon”, “kind of soon”, or “not soon”; or that the item is “inactive”
	- [x] This urgency indicator *does not* rely on only color
- [ ] `api/firestore.js` exports a new `comparePurchaseUrgency` function with the following behaviors
	- [x] sorts inactive items last, then
	- [x] sorts items in ascending order of days until purchase, and
	- [x] sorts items with the same days until purchase alphabetically

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before

<img width="1399" alt="Screenshot 2023-09-20 at 10 01 13 AM" src="https://github.com/the-collab-lab/tcl-62-smart-shopping-list/assets/49603115/40a08a85-a04c-42ce-aec7-3949978c3892">

### After

<img width="1424" alt="Screenshot 2023-09-20 at 10 01 31 AM" src="https://github.com/the-collab-lab/tcl-62-smart-shopping-list/assets/49603115/ea445dac-7338-485a-8a29-3d2558065ef5">

## Testing Steps / QA Criteria
Sure, here are those steps explained in simpler terms:

1. Go to the `main` branch in your code and get all the latest changes by using the command `git pull`. Then, switch to the `as-ms-sort-list`branch.
2. Start your development environment by running the command `npm start`.
3. Click on the "Create New List" button and then click on the "+Add Item" button.
4. Begin adding items to the list.
5. Look at the list, and you'll see that each item has a special mark that shows when you should buy it.
6. Check  and remember your token name: To do it go to dev tools > Application > Local Storage
7. To test if items are sorted correctly, change the dates of some items in your Firestore database. For example, add "potatoes" and change its "dateCreated" to July 2, 2023, at 10:11:21 AM UTC-7, "dateLastPurchased" to July 10, 2023, at 10:23:47 AM UTC-7, and "dateNextPurchased" to September 30, 2023, at 10:36:14 AM UTC-7. The item should now appear as inactive and be displayed at the end of the list.
8. To see the indicator "Not Soon", add an item like "ice cream" in Firebase and change its dates in the database. For example, set "dateCreated" to September 18, 2023, at 10:10:30 AM UTC-7, "dateLastPurchased" to September 18, 2023, at 10:38:08 AM UTC-7, and "dateNextPurchased" to September 19, 2023, at 10:38:14 AM UTC-7.
9. To check if items are sorted alphabetically, add two items to the list, for instance, "bread" and "brussels sprouts." Check if "bread" appears before "brussels sprouts" in the list when they have the same label.

2023-09-22 02:39 UTC, codecaviette approved these changes
Feature works as expected. Nice work!

One question-- One of the AC states, "This urgency indicator does not rely on _only_ color". My interpretation of this is that the urgency should be indicated by a color _and_ a written indicator (which you've included); however, I'm not seeing any variance in color. This could be a misinterpretation on my part, but may be worth confirming with the mentors in order to meet the AC requirements.

2023-09-22 17:54 UTC, hajschroeder requested changes
`getDaysBetweenDates` in '../utils/dates.js' is returning the difference in days as a real number with a decimal beyond the trillions.  This value is calculated from the moment the code compiles after a user adds an item, and is returning the days between with a precision of 10<sup>-15</sup>. A 30 day difference, for example, is returning a precise difference of  29.999xxxxxxxxxx, so items that should be labeled as "Not Soon" are still registering as being <30 days old, and thus rendering as "Kind Of Soon". Wrapping `Math.round()` around either the `daysToNextPurchase` calculation in line 36 of ListItem.jsx, or around the `differenceInDays` calculation on line 18 of '..utils.dates.js' is a quick fix

2023-09-22 17:54 UTC, hajschroeder commented on src/components/ListItem.jsx
> +		const daysToNextPurchase = getDaysBetweenDates(
Convert this value to an integer either here, or wrap `Math.round()` around the calculation of the return constant in `getDaysBetweenDates` from '../utils.dates.js' 
```suggestion
		const daysToNextPurchase = Math.round(getDaysBetweenDates(...
```

2023-09-23 02:29 UTC, hajschroeder approved these changes

2023-09-23 02:30 UTC, hajschroeder commented
Approved, but there just needs a quick syntax fix on line 39 of ListItem.jsx, needa a closing parenthetical. I updated my comment to reflect this

2023-09-23 18:58 UTC, lyleschemmerling commented
It looks like this is working but there is a bug in how we handle a clicked item where the dateNextPurchased on new items is "Today" and not the time in the future appropriate for the item which results in items I just clicked being sorted to the top of the list.
![Screenshot from 2023-09-23 12-57-13](https://github.com/the-collab-lab/tcl-62-smart-shopping-list/assets/11809481/339e3004-997a-49b1-9dbe-160a0cc03b4b)

2023-09-24 00:11 UTC, thetrend approved these changes

2023-09-24 00:14 UTC, jeremiahfallin approved these changes

2023-09-24 16:47 UTC, lyleschemmerling approved these changes

2023-09-25 16:37 UTC, merged